# Generated by Django 2.2 on 2020-05-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_user_id', models.CharField(max_length=30)),
                ('wb_user_id', models.CharField(max_length=30)),
                ('user_customize_score', models.IntegerField(default=0)),
                ('info', models.TextField(null=True)),
            ],
        ),
    ]
