# Generated by Django 2.2 on 2020-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('registration_time', models.CharField(max_length=20)),
                ('sunshine', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=140)),
                ('profile_url', models.CharField(max_length=200)),
                ('profile_image_url', models.CharField(max_length=200)),
                ('avatar_hd', models.CharField(max_length=200)),
                ('verified_reason', models.CharField(max_length=140)),
            ],
        ),
    ]
