# Generated by Django 2.2 on 2020-05-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mbrank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='statuses_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='urank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_type',
            field=models.IntegerField(default=0),
        ),
    ]
