# Generated by Django 2.2 on 2020-05-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboUser', '0002_auto_20200505_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
