# Generated by Django 2.2 on 2020-05-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bid', models.CharField(max_length=12)),
                ('user_id', models.CharField(max_length=20)),
                ('screen_name', models.CharField(max_length=30)),
                ('topics', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=30)),
                ('retweet_id', models.CharField(max_length=20)),
            ],
        ),
    ]
