# Generated by Django 2.2 on 2020-05-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboEntity', '0002_auto_20200505_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibo',
            name='userid',
        ),
        migrations.AlterField(
            model_name='weibo',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
