# Generated by Django 2.2 on 2020-05-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboEntity', '0003_auto_20200505_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='attitudes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weibo',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weibo',
            name='reposts_count',
            field=models.IntegerField(default=0),
        ),
    ]
