# Generated by Django 2.2 on 2020-05-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboEntity', '0005_auto_20200505_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
    ]
