# Generated by Django 2.2 on 2020-05-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboEntity', '0006_weibo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
