# Generated by Django 2.2 on 2020-05-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboEntity', '0007_auto_20200505_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
