# Generated by Django 2.2 on 2020-05-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboEntity', '0008_auto_20200505_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo',
            name='at_users',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='pics',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='video_url',
            field=models.TextField(null=True),
        ),
    ]
